name: CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install Django

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build and run Docker Compose
      run: |
        docker-compose up 

    - name: Stop Docker Compose
      if: always()
      run: docker-compose down